// Mock Product Data
import type { ValueCards } from '../../components/types/ValueCards';

export const getMockProducts = (): ValueCards[] => {
  return [
    {
      id: 1,
      title: 'Адвент календарь профессиональная косметика',
      description: 'Премиум адвент календарь с профессиональной косметикой для ухода за лицом и телом. Идеальный подарок для праздника.',
      sku: 'ADV-COSM-001',
      purchasePrice: 250,
      retailPrice: 500,
      price: 500,
      image: '',
      count: 55,
      category: 'cosmetics',
      margin: 100,
      isActive: true,
      isArchived: false,
      createdAt: '2024-01-15T10:00:00Z',
      updatedAt: '2024-03-20T14:30:00Z',
    },
    {
      id: 2,
      title: 'Подарочный набор для женщин',
      description: 'Роскошный подарочный набор, содержащий косметику и аксессуары для женщин. Упаковано в красивую подарочную коробку.',
      sku: 'GIFT-WOMAN-001',
      purchasePrice: 1500,
      retailPrice: 3000,
      price: 3000,
      image: '',
      count: 66,
      category: 'cosmetics',
      margin: 100,
      isActive: true,
      isArchived: false,
      createdAt: '2024-01-20T10:00:00Z',
      updatedAt: '2024-03-19T09:15:00Z',
    },
    {
      id: 3,
      title: 'Сладкий предновогодний набор',
      description: 'Ассортимент рождественских сладостей включает шоколад, печенье и мармелад высокого качества.',
      sku: 'SWEET-XMAS-001',
      purchasePrice: 350,
      retailPrice: 700,
      price: 3000,
      image: '',
      count: 25,
      category: 'candy',
      margin: 100,
      isActive: true,
      isArchived: false,
      createdAt: '2024-02-01T10:00:00Z',
      updatedAt: '2024-03-21T16:45:00Z',
    },
    {
      id: 4,
      title: 'Мягкая игрушка Мишка',
      description: 'Мягкая игрушка мишка, сделанная из высококачественного плюша. Безопасна для детей, веселая и уютная.',
      sku: 'TOY-BEAR-001',
      purchasePrice: 200,
      retailPrice: 450,
      price: 450,
      image: '',
      count: 42,
      category: 'toys',
      margin: 125,
      isActive: true,
      isArchived: false,
      createdAt: '2024-02-10T10:00:00Z',
      updatedAt: '2024-03-18T11:20:00Z',
    },
    {
      id: 5,
      title: 'Парфюм "Зимний натиск"',
      description: 'Изысканный парфюм с ароматом зимних специй, ванили и мускуса. Долгоиграющий аромат, подходит для любого времени года.',
      sku: 'PERF-WINTER-001',
      purchasePrice: 800,
      retailPrice: 2000,
      price: 2000,
      image: '',
      count: 12,
      category: 'parfume',
      margin: 150,
      isActive: true,
      isArchived: false,
      createdAt: '2024-02-15T10:00:00Z',
      updatedAt: '2024-03-20T08:00:00Z',
    },
    {
      id: 6,
      title: 'Рождественская кофта',
      description: 'Теплая и уютная вязаная кофта с рождественским узором. Идеальна для праздничных вечеров и встреч.',
      sku: 'CLOTH-XMAS-001',
      purchasePrice: 600,
      retailPrice: 1500,
      price: 1500,
      image: '',
      count: 38,
      category: 'cloth',
      margin: 150,
      isActive: true,
      isArchived: false,
      createdAt: '2024-02-20T10:00:00Z',
      updatedAt: '2024-03-19T13:30:00Z',
    },
    {
      id: 7,
      title: 'Снежинка декоративная',
      description: 'Красивая декоративная снежинка для украшения дома. Сделана из качественного материала, прекрасно выглядит на окне.',
      sku: 'DECOR-SNOW-001',
      purchasePrice: 50,
      retailPrice: 150,
      price: 150,
      image: '',
      count: 120,
      category: 'decoration',
      margin: 200,
      isActive: true,
      isArchived: false,
      createdAt: '2024-03-01T10:00:00Z',
      updatedAt: '2024-03-20T10:00:00Z',
    },
    {
      id: 8,
      title: 'Набор украшений на ёлку',
      description: 'Набор из 12 разноцветных шаров и 5 звезд для украшения рождественской ёлки. Надежные крепления, яркие цвета.',
      sku: 'DECOR-TREE-001',
      purchasePrice: 300,
      retailPrice: 750,
      price: 750,
      image: '',
      count: 18,
      category: 'decoration',
      margin: 150,
      isActive: true,
      isArchived: false,
      createdAt: '2024-03-02T10:00:00Z',
      updatedAt: '2024-03-21T15:00:00Z',
    },
  ];
};

export const getMockProductById = (id: number): ValueCards | undefined => {
  return getMockProducts().find(p => p.id === id);
};
